### ISSUE TITLE
Remove ability to add something without foreign key

### ISSUE THREAD

**Issue by Sirtario** [Sirtario/DB2Praktikum#18]

**Comment by reichts** [comment]
Aktuell werden um foreignKeys-Beziehungen umzusetzen, ComboBoxen durch Methoden wie populateRaumBox() in addBettController befüllt, diese rufen alle returnForeignKeys() in Datenbank.java auf, wenn es aber nocht keine passenden Einträge gibt (wenn es zum Beispiel noch keine Räume gibt, um das Beispiel fortzusetzten) ein String ("Hier ist nichts!") in die ComboBox geladen
trotzdem kann man 'save' in dem Fenster drücken, dann kommt aber eine SQLException

**Comment by reichts** [comment]
Möglichkeit das zu fixen:
-in den jeweiligen onClickSaveEntry()-Methoden um die querry eine if-Abfrage einbauen, die überprüft ob irgend ein Wert mit Null, empty, oder "Hier ist nichts!" belegt ist und dann einen Alert zu schmeißen
-schon beim öffnen des add-Fensters den 'save' button ausgrauen, wenn irgend eine der listen noch leer ist

**Comment by reichts** [comment]
die Erste Möglichkeit wird am einfachsten sein, die zweite müsste mehr als einmal gegen Demeter verstoßen, um die gut umzusetzen

**Comment by reichts** [comment]
bei der ersten könnte man auch direkt überprüfen, ob ein Datum und die Textfelder noch leer sind
